name: Build & Deploy to CapRover

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Empaquetamos SOLO lo que necesita CapRover para construir la imagen
      - name: Create deployment tar
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            apps/
            config/
            database/
            manage.py
            requirements.txt
            Dockerfile
            captain-definition
            .env.example
          outPath: deploy.tar

      # Deploy usando la acci√≥n oficial de CapRover
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ secrets.APP_NAME }}'
            token: '${{ secrets.APP_TOKEN }}'
            tarFile: 'deploy.tar'
